org: marianofndz
app: backend-appsync
service: backend-appsync

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-dotenv-plugin
  - serverless-appsync-plugin
  - serverless-esbuild
  - serverless-offline
  - serverless-appsync-simulator
  - serverless-prune-plugin